### PR TITLE
Add forecast 2023-09-04 UC3M-EpiGraph

### PR DESCRIPTION
**Pull request by epigraph-forecast**

### CODE REVIEW

**Comment by reneniehus** [comment]
Hi David and team, I checking the visual of your forecast, and wondering if it is a feature or a bug of the model that the same mean and range values are being predicted for all future time points. See:

https://forecasthub.shinyapps.io/covid19-forecast-hub-europe//?file=https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/raw/aca9fed2aa8e8838bd7dcfcd0b69689f2453cd22/data-processed/UC3M-EpiGraph/2023-09-04-UC3M-EpiGraph.csv

**Comment by reneniehus** [comment]
@epigraph-forecast , tagging you in this comment. Please have a look at the forecasts and let me know if they are ok from your side.

**Comment by epigraph-forecast** [comment]
Hi @reneniehus, there was a small error in the target_end_date column (the date was Tuesday instead of Saturday). We just corrected it and committed the changes.

**Review by reneniehus — COMMENTED** [review]
Thank you @epigraph-forecast for looking into this. This is now merged.

**Pull request merged**
