### PR TITLE
prolix 

### PR DESCRIPTION
**Pull request by loicpottier**
last try before draft if error

### CODE REVIEW

**Comment by loicpottier** [comment]
Should be right, now. Thank you for your work. 
Loïc Pottier

**Comment by kathsherratt** [comment]
Hi Loïc Pottier @loicpottier - thank you for contributing to the hub!

This PR looks great. We merge all submissions together on Tuesday mornings, and the visualisations on the [website](https://covid19forecasthub.eu/index.html) are updated shortly after that. After four weeks of submissions, you will also see your model in the [evaluation reports](https://covid19forecasthub.eu/reports.html).

You are very welcome to join our mailing list, which we use to organise meetings for all participants in the hub every other week. If you are interested, please request to join here: https://groups.google.com/u/1/g/euro-covid19-forecast-hub

Best wishes,
Kath

**Comment by loicpottier** [comment]
Hi Katt Sherratt,
i dont see may forecats in the visualizations: https://covid19forecasthub.eu/visualisation.html
Should i wait tomorrow?
Best regards,
Loïc Pottier

**Comment by kathsherratt** [comment]
Hi Loïc @loicpottier , 

Thank you again for your forecasts. I can see them on the main website, although by default we show the ensemble model. To see your forecast you may need to select your model under the "display settings" on the right-hand side.

Best wishes,
Kath

image

**Comment by loicpottier** [comment]
Hi Kath,

in fact when i click on View forecasts on the website, i get briefly a 404 error page, then there is a loading page and then the visualizations  for 
Forecasts · Cases, France  · issued on Dec 27, 2021

Strange...?
Loïc

**Comment by loicpottier** [comment]
Hi Kath,

in fact when i click on View forecasts on the website, i get briefly a 404 error page, then there is a loading page and then the visualizations  for 
Forecasts · Cases, France  · issued on Dec 27, 2021

Strange...?
Loïc


> Hi Loïc @loicpottier ,
> 
> Thank you again for your forecasts. I can see them on the main website, although by default we show the ensemble model. To see your forecast you may need to select your model under the "display settings" on the right-hand side.
> 
> Best wishes, Kath
> 
> image

**Comment by loicpottier** [comment]
It's ok now :)

> Hi Kath,
> 
> in fact when i click on View forecasts on the website, i get briefly a 404 error page, then there is a loading page and then the visualizations for Forecasts · Cases, France · issued on Dec 27, 2021
> 
> Strange...? Loïc

**Pull request merged**
